name: gitlabels-test

permissions:
  issues: write

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitlabels/gitlabels-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
